# Generated by Django 4.0.6 on 2022-07-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movies_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='pub_date',
        ),
    ]
